# Ceph installed through a new repository
ceph_origin: repository
# fetches packages from http://download.ceph.com, the official community Ceph repositories
ceph_repository: community
ceph_repository_type: cdn

ceph_stable_release: luminous

public_network: "172.21.0.0/24"
cluster_network: "172.21.0.0/24"

ntp_service_enabled: true
ntp_daemon_type: ntpd

osd_objectstore: bluestore
osd_scenario: lvm
devices:
  - /dev/sdb

ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 32
    osd_pool_default_pgp_num: 32
    osd_journal_size: 1024
    osd_pool_default_size: 3
    osd_pool_default_min_size:  2
